name: Build and Release

on:
  push:
    tags:
      - '*'  # 触发条件：推送以'v'开头的标签

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build executables
      run: |
        # 检查是否有图标文件
        if (Test-Path "src/app-icon.ico") {
          # 构建主程序（带图标）
          pyinstaller --onefile --windowed --icon=src/app-icon.ico --name=open_folder_with_obsidian src/main.py
          
          # 构建安装程序（带图标）
          pyinstaller --onefile --windowed --icon=src/app-icon.ico --name=obsidian_installer src/installer.py
        } else {
          # 构建主程序（无图标）
          pyinstaller --onefile --windowed --name=open_folder_with_obsidian src/main.py
          
          # 构建安装程序（无图标）
          pyinstaller --onefile --windowed --name=obsidian_installer src/installer.py
        }
        
        # 清理build目录
        Remove-Item -Recurse -Force build -ErrorAction SilentlyContinue
        Remove-Item -Force *.spec -ErrorAction SilentlyContinue
        
    - name: Verify build results
      run: |
        echo "=== 验证构建结果 ==="
        echo "dist目录内容:"
        Get-ChildItem dist/
        echo ""
        echo "检查exe文件是否存在:"
        if (Test-Path "dist/open_folder_with_obsidian.exe") {
          echo "✓ open_folder_with_obsidian.exe 存在"
        } else {
          echo "✗ open_folder_with_obsidian.exe 不存在"
          exit 1
        }
        
        if (Test-Path "dist/obsidian_installer.exe") {
          echo "✓ obsidian_installer.exe 存在"
        } else {
          echo "✗ obsidian_installer.exe 不存在"
          exit 1
        }
        
        echo "构建验证完成"
        
    - name: Create version info
      run: |
        # 创建版本信息文件到dist目录
        $VERSION = $env:GITHUB_REF -replace 'refs/tags/', ''
        if (-not $VERSION) { $VERSION = "dev" }
        
        $BUILD_TIME = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
        $COMMIT_SHA = $env:GITHUB_SHA
        
        $README_CONTENT = @"
        Obsidian文件夹打开器 $VERSION
        
        构建时间: $BUILD_TIME
        提交: $COMMIT_SHA
        
        文件说明:
        - open_folder_with_obsidian.exe: 主程序，用于打开文件夹
        - obsidian_installer.exe: 安装程序，用于设置右键菜单
        
        使用方法:
        1. 以管理员身份运行 obsidian_installer.exe 进行安装
        2. 安装完成后即可在任意文件夹右键选择"用Obsidian打开"
"@
        
        Set-Content -Path "dist/README.md" -Value $README_CONTENT -Encoding UTF8
        
    - name: Create zip package
      run: |
        echo "=== 创建zip包 ==="
        $VERSION = $env:GITHUB_REF -replace 'refs/tags/', ''
        if (-not $VERSION) { $VERSION = "dev" }
        echo "版本: $VERSION"
        
        Set-Location dist
        echo "当前目录: $(Get-Location)"
        echo "要打包的文件:"
        Get-ChildItem *.exe, *.md
        
        # 使用PowerShell的Compress-Archive创建zip包
        $ZIP_NAME = "obsidian-folder-opener-${VERSION}.zip"
        Compress-Archive -Path "open_folder_with_obsidian.exe", "obsidian_installer.exe", "README.md" -DestinationPath $ZIP_NAME -Force
        
        echo "zip包创建完成:"
        Get-ChildItem *.zip
        
        # 验证zip包内容
        echo "验证zip包内容:"
        $ZIP_ARCHIVE = [System.IO.Compression.ZipFile]::OpenRead($ZIP_NAME)
        $ZIP_ARCHIVE.Entries | ForEach-Object { echo $_.Name }
        $ZIP_ARCHIVE.Dispose()
        
        Set-Location ..
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: obsidian-folder-opener-windows
        path: dist/
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
        discussion_category_name: "Announcements"
        body: |
          ## Obsidian文件夹打开器 ${{ github.ref_name }}          
          ---
        files: |
          dist/obsidian-folder-opener-*.zip
          dist/open_folder_with_obsidian.exe
          dist/obsidian_installer.exe
          dist/README.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
